{
 "title": "Support Bot",
 "time": { "from": "now-2m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Per-replica QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ray_serve_num_http_requests{route=\"/chat\"}[2m])",
     "legendFormat": "HTTP Proxy"
    },
    {
     "expr": "rate(ray_serve_backend_request_counter{backend=\"IntentClassifier\"}[2m])",
     "legendFormat": "Intent Classifier"
    },
    {
     "expr": "rate(ray_serve_backend_request_counter{backend=\"RelevanceSearch\"}[2m])",
     "legendFormat": "Relevance Search"
    }
   ]
  },
  {
   "title": "p95 Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(ray_serve_backend_processing_latency_ms_bucket{backend=\"ChatBot\"}[1m])) by (le))",
     "legendFormat": "End-to-end"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ray_serve_backend_processing_latency_ms_bucket{backend=\"IntentClassifier\"}[1m])) by (le))",
     "legendFormat": "Intent Classifier"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(ray_serve_backend_processing_latency_ms_bucket{backend=\"RelevanceSearch\"}[1m])) by (le))",
     "legendFormat": "Relevance Search"
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "4.5 * (sum(ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"}) / sum(ray_node_cpu_count{instance=~\"$Instance\"}))",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "8.5 * (sum(ray_node_mem_used{instance=~\"$Instance\"}) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\"}))",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\"}) * 100 / sum(ray_node_disk_usage{instance=~\"$Instance\"} + ray_node_disk_free{instance=~\"$Instance\"})",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} * 100 / ray_node_gpus_available{instance=~\"$Instance\"}",
     "legendFormat": "GPUs Utilization"
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\"}",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"} / (ray_node_disk_utilization_percentage{instance=~\"$Instance\"} / 100)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}